# Generated by Django 5.0.7 on 2024-07-27 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('sum_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('exhibition', '展示'), ('lantern', '行燈'), ('banner', '垂れ幕'), ('cm', 'クラスCM')], default='exhibition', unique=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_wallet_web.purchase')),
            ],
        ),
    ]
